name: Publish to npm on version change

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4

      - name: Get previous commit
        id: prev
        run: echo "commit=$(git rev-parse HEAD^)" >> "$GITHUB_OUTPUT"

      - name: Get previous version
        id: prev_version
        run: |
          git show ${{ steps.prev.outputs.commit }}:package.json > prev-package.json
          echo "version=$(jq -r .version prev-package.json)" >> "$GITHUB_OUTPUT"

      - name: Get current version
        id: curr_version
        run: |
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Compare versions
        id: compare
        run: |
          echo "prev=${{ steps.prev_version.outputs.version }}"
          echo "curr=${{ steps.curr_version.outputs.version }}"
          if [ "${{ steps.prev_version.outputs.version }}" = "${{ steps.curr_version.outputs.version }}" ]; then
            echo "No version change, exiting."
            echo "publish=false" >> "$GITHUB_OUTPUT"
          else
            echo "Version changed, will publish."
            echo "publish=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node.js
        if: steps.compare.outputs.publish == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        if: steps.compare.outputs.publish == 'true'
        run: npm ci

      - name: Build
        if: steps.compare.outputs.publish == 'true'
        run: npm run build

      - name: Publish to npm
        if: steps.compare.outputs.publish == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
